Repository Telecominfraproject/wlan-cloud-rrm, pull requests merged in 2022-11, with the labels that each got.

#116 Add station pinger to RRM service
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralClient.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/kafka/UCentralKafkaConsumer.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/State.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/RRM.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/RRMConfig.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/modules/Modeler.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/rca/RCAConfig.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/rca/RCAUtils.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/rca/modules/StationPinger.java
Labels: enhancement

#120 Update gitignore
  .gitignore
  owrrm/.gitignore
Labels: enhancement

#123 Add rca params
  lib-rca/src/main/java/com/facebook/openwifi/librca/inputs/RCAParams.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/rca/modules/StationPinger.java
Labels: enhancement

#126 Fix several compile errors/warnings
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/AggregatedState.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/SingleAPBandSteering.java
  owrrm/src/test/java/com/facebook/openwifi/rrm/modules/ModelerUtilsTest.java
  owrrm/src/test/java/com/facebook/openwifi/rrm/modules/ProvMonitorTest.java
Labels: bug

#128 Client steering notes, docs, fixes
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/IEUtils.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/InformationElements.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/ies/RMEnabledCapabilities.java
  owrrm/ALGORITHMS.md
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringOptimizer.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/ClientSteeringState.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/SingleAPBandSteering.java
Labels: enhancement

#129 Remove device config schema copy in ConfigManager
  owrrm/src/main/java/com/facebook/openwifi/rrm/modules/ConfigManager.java
Labels: enhancement

#130 Add UCentralSchema and convert Modeler.DataModel.latestDeviceStatusRadios
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralApConfiguration.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/UCentralUtils.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/UCentralSchema.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/modules/Modeler.java
  owrrm/src/test/java/com/facebook/openwifi/rrm/optimizers/TestUtils.java
Labels: enhancement

#131 Add package-info.java and other class-level javadocs
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/ies/package-info.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/kafka/package-info.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/Capabilities.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/State.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/UCentralSchema.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/WifiScanEntryResult.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/ap/package-info.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/gw/package-info.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/prov/package-info.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/models/prov/rrm/package-info.java
  lib-cloudsdk/src/main/java/com/facebook/openwifi/cloudsdk/package-info.java
  lib-rca/src/main/java/com/facebook/openwifi/librca/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/modules/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/channel/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/clientsteering/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/optimizers/tpc/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/package-info.java
  owrrm/src/main/java/com/facebook/openwifi/rrm/rca/package-info.java
  pom.xml
Labels: documentation
