Repository Telecominfraproject/wlan-cloud-rrm, pull requests merged in 2022-08, with the labels that each got.

#19 [WIFI-9980] Add RRM scheduler
  IMPLEMENTATION.md
  pom.xml
  src/main/java/com/facebook/openwifirrm/DeviceConfig.java
  src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
  src/main/java/com/facebook/openwifirrm/RRM.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/RRMSchedule.java
  src/main/java/com/facebook/openwifirrm/Utils.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/java/com/facebook/openwifirrm/modules/Modeler.java
  src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
  src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
  src/test/java/com/facebook/openwifirrm/DeviceDataManagerTest.java
  src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
  src/test/java/com/facebook/openwifirrm/modules/ProvMonitorTest.java
Labels: enhancement

#20 [WIFI-9985] Generate openapi.yaml during mvn compile
  README.md
  openapi.yaml
  pom.xml
Labels: enhancement

#21 [WIFI-9987] Improve OpenWiFi auth
  openapi.yaml
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/Utils.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
Labels: enhancement

#22 Misc fixes
  src/main/java/com/facebook/openwifirrm/RRM.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
  src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
  src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApApTPC.java
  src/test/java/com/facebook/openwifirrm/modules/ProvMonitorTest.java
Labels: bug

#23 Generate version.txt via maven
  pom.xml
  src/main/java/com/facebook/openwifirrm/Launcher.java
  src/main/java/com/facebook/openwifirrm/RRM.java
  src/main/java/com/facebook/openwifirrm/Utils.java
  src/main/java/com/facebook/openwifirrm/VersionProvider.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/resources-filtered/version.txt
  src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
Labels: enhancement

#26 Improve error handling in UCentralApConfiguration
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralApConfiguration.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
Labels: bug

#27 Upgrade Swagger UI from v3.52.3 to v4.13.2
  src/main/resources/public/index.css
  src/main/resources/public/index.html
  src/main/resources/public/oauth2-redirect.html
  src/main/resources/public/swagger-initializer.js
  src/main/resources/public/swagger-ui-bundle.js
  src/main/resources/public/swagger-ui-es-bundle-core.js
  src/main/resources/public/swagger-ui-es-bundle.js
  src/main/resources/public/swagger-ui-standalone-preset.js
  src/main/resources/public/swagger-ui.css
  src/main/resources/public/swagger-ui.js
Labels: enhancement

#28 [WIFI-10341] Implement owprov RRM API
  ALGORITHMS.md
  openapi.yaml
  src/main/java/com/facebook/openwifirrm/RRM.java
  src/main/java/com/facebook/openwifirrm/RRMAlgorithm.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/RRMSchedule.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/java/com/facebook/openwifirrm/modules/RRMScheduler.java
  src/main/java/com/facebook/openwifirrm/optimizers/ChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/optimizers/LeastUsedChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/optimizers/LocationBasedOptimalTPC.java
  src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApApTPC.java
  src/main/java/com/facebook/openwifirrm/optimizers/MeasurementBasedApClientTPC.java
  src/main/java/com/facebook/openwifirrm/optimizers/RandomChannelInitializer.java
  src/main/java/com/facebook/openwifirrm/optimizers/RandomTxPowerInitializer.java
  src/main/java/com/facebook/openwifirrm/optimizers/UnmanagedApAwareChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/ucentral/prov/rrm/models/Algorithm.java
  src/main/java/com/facebook/openwifirrm/ucentral/prov/rrm/models/Provider.java
  src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
Labels: enhancement

#29 OpenAPI fixes
  openapi.yaml
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/resources/public/swagger-initializer.js
Labels: bug

#31 Configure javadoc, fix errors, deploy to gh-pages
  .github/workflows/deploy-gh-pages.yml
  README.md
  pom.xml
  src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
  src/main/java/com/facebook/openwifirrm/Launcher.java
  src/main/java/com/facebook/openwifirrm/RRMAlgorithm.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/java/com/facebook/openwifirrm/optimizers/TPC.java
  src/main/javadoc/overview.html
Labels: documentation

#32 [WIFI-9985] Add CORS support
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
Labels: enhancement

#33 Update package version to 2.7.0, append git info during docker builds
  Dockerfile
  openapi.yaml
  pom.xml
  scripts/get_build_version.sh
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/resources-filtered/version.txt
Labels: enhancement

#25 Aggregate wifiscans
  src/main/java/com/facebook/openwifirrm/aggregators/Aggregator.java
  src/main/java/com/facebook/openwifirrm/aggregators/MeanAggregator.java
  src/main/java/com/facebook/openwifirrm/modules/DataCollector.java
  src/main/java/com/facebook/openwifirrm/modules/Modeler.java
  src/main/java/com/facebook/openwifirrm/modules/ModelerUtils.java
  src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
  src/main/java/com/facebook/openwifirrm/optimizers/ChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralKafkaConsumer.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
  src/main/java/com/facebook/openwifirrm/ucentral/models/WifiScanEntryResult.java
  src/main/java/com/facebook/openwifirrm/ucentral/operationelement/HTOperationElement.java
  src/main/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElement.java
  src/test/java/com/facebook/openwifirrm/aggregators/MeanAggregatorTest.java
  src/test/java/com/facebook/openwifirrm/modules/ModelerUtilsTest.java
  src/test/java/com/facebook/openwifirrm/optimizers/LeastUsedChannelOptimizerTest.java
  src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
  src/test/java/com/facebook/openwifirrm/ucentral/operationelement/HTOperationElementTest.java
  src/test/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElementTest.java
Labels: enhancement

#34 Move SSL validation toggle into RRMConfig
  src/main/java/com/facebook/openwifirrm/Launcher.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
Labels: enhancement

#36 Fix javadoc errors from #25
  src/main/java/com/facebook/openwifirrm/aggregators/Aggregator.java
  src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
Labels: bug

#37 Update documentation
  IMPLEMENTATION.md
  README.md
  diagram.svg
Labels: documentation

#40 Fix build version generation in CI/CD
  .github/workflows/ci.yml
  scripts/get_build_version.sh
Labels: bug

#39 Move Kafka consumer poll timeout to RRMConfig
  src/main/java/com/facebook/openwifirrm/Launcher.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralKafkaConsumer.java
Labels: enhancement

#41 Use ht operation element class decoder
  src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/ucentral/operationelement/HTOperationElement.java
  src/main/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElement.java
  src/test/java/com/facebook/openwifirrm/ucentral/operationelement/VHTOperationElementTest.java
Labels: enhancement

#38 Multi band for MeasurementBasedApApTPC
  src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/optimizers/channel/LeastUsedChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/TPC.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralConstants.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
  src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
  src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
Labels: enhancement

#42 Add missing device connection status checks in DataCollector
  src/main/java/com/facebook/openwifirrm/modules/DataCollector.java
Labels: bug

#46 Update README and other docs
  ALGORITHMS.md
  IMPLEMENTATION.md
  README.md
Labels: documentation

#49 Add autoformatter (Spotless with Maven, Eclipse JDT)
  README.md
  pom.xml
  spotless/eclipse-java-formatter.xml
  spotless/license-header.txt
  src/main/java/com/facebook/openwifirrm/DeviceDataManager.java
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/main/java/com/facebook/openwifirrm/modules/ProvMonitor.java
  src/main/java/com/facebook/openwifirrm/mysql/DatabaseManager.java
  src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/LocationBasedOptimalTPC.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralClient.java
  src/test/java/com/facebook/openwifirrm/modules/DataCollectorTest.java
  src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
Labels: enhancement

#52 Set thread names
  src/main/java/com/facebook/openwifirrm/RRM.java
  src/main/java/com/facebook/openwifirrm/Utils.java
  src/main/java/com/facebook/openwifirrm/modules/DataCollector.java
Labels: enhancement

#55 Use UCentralUtils.isChannelInBand()
  src/main/java/com/facebook/openwifirrm/optimizers/channel/ChannelOptimizer.java
Labels: enhancement

#47 [WIFI-10593] Allow different values per AP for `RandomChannelInitializer` and `RandomTxPowerInitializer`
  src/main/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializer.java
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializer.java
  src/test/java/com/facebook/openwifirrm/optimizers/channel/RandomChannelInitializerTest.java
  src/test/java/com/facebook/openwifirrm/optimizers/tpc/RandomTxPowerInitializerTest.java
Labels: enhancement

#54 Add multi-band check for MeasurementBasedApApTPC
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPC.java
  src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
  src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApApTPCTest.java
Labels: bug

#51 Enable MeasurementBasedApClientTPC in 2G
  src/main/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPC.java
  src/main/java/com/facebook/openwifirrm/ucentral/UCentralUtils.java
  src/test/java/com/facebook/openwifirrm/optimizers/TestUtils.java
  src/test/java/com/facebook/openwifirrm/optimizers/tpc/MeasurementBasedApClientTPCTest.java
Labels: enhancement

#63 remove basic auth
  IMPLEMENTATION.md
  src/main/java/com/facebook/openwifirrm/RRMConfig.java
  src/main/java/com/facebook/openwifirrm/modules/ApiServer.java
  src/test/java/com/facebook/openwifirrm/modules/ApiServerTest.java
Labels: enhancement
